
image: node:latest

cache:
  paths:
    - frontend/node_modules/



test-frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test -- --coverage

build-frontend:
  environment:
    - REACT_APP_BACKEND=https://teamproject.lorneb.com
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
