
image: node:latest


stages:
 - build 
 - test


cache:
  paths:
    - frontend/node_modules/


# build-frontend:
#   stage: build
#   script:
#     - cd frontend
#     - npm install
#     - npm run build


test-frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test -- --coverage



build-backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind    
  script: docker compose build backend


test-backend:
  stage: test
  image: backend
  services:
    - docker:dind    
  script:
    - docker compose build backend
    - docker compose up backend -d
    - docker compose exec backend "python manage.py test"


