before_script:
  - docker info

build-docker:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

test-job1:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
