version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
    environment:
      - DATABASE_NAME=wow
        DATABASE_USER=postgres
        DATABASE_PASSWORD=postgres
        DATABASE_HOST=localhost
        DATABASE_PORT=5432
    ports:
      - 8000:8000
volumes:
  db:
    driver: local
