# Generated by Django 4.1.2 on 2023-02-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WindmillType',
            fields=[
                ('modelId', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.TextField()),
                ('power_curve_input', models.JSONField()),
                ('power_curve_output', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('weatherId', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('value_type', models.TextField()),
                ('time', models.DateTimeField()),
                ('source', models.TextField()),
                ('unit_of_measurement', models.TextField()),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('value_type', 'time', 'source', 'location_x', 'location_y')},
            },
        ),
        migrations.CreateModel(
            name='UserTurbines',
            fields=[
                ('turbineId', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('modelId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_backend.windmilltype')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
