# Generated by Django 4.1.2 on 2023-02-11 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userturbines',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='windmilltype',
            name='manufacturer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userturbines',
            unique_together={('userId', 'name')},
        ),
    ]
