# Generated by Django 4.1.2 on 2023-02-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0002_userturbines_name_windmilltype_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windmilltype',
            name='display_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
